### ISSUE TITLE
worddetailのフロント実装

### ISSUE THREAD

**Issue by tomoki171923** [tomoki171923/e2e#32]

**Comment by yukarri805** [comment]
智紀の Go が出次第の実装

**Comment by tomoki171923** [comment]
#47 
が完了次第始めてください

**Comment by tomoki171923** [comment]
#47 
完了しているので作業開始できます。

**Comment by tomoki171923** [comment]
ページのイメージは以下。
https://docs.google.com/presentation/d/1peq1_ZAOURdcDBLXZjrHqXiVCvdxI8u9_4OSsG6UISw/edit#slide=id.p

**Comment by tomoki171923** [comment]
#83 
で一旦マージ。残タスクあり。

**Comment by tomoki171923** [comment]
#86 
でリファクタ済み。各要素にcssが当たるはずです。

**Comment by tomoki171923** [comment]
#89 
でマージ済み。クローズする。
