### ISSUE TITLE
パンくずリスト作成

### ISSUE THREAD

**Issue by tomoki171923** [tomoki171923/e2e#58]

**Comment by yukarri805** [comment]
参考：https://saruwakakun.com/html-css/basic/breadcrumb

**Comment by yukarri805** [comment]
パンクズリスト→実装：breadcrumbs_on_rails
やりたいこと→googleの構造化データで読みとれるようにする
https://search.google.com/structured-data/testing-tool/u/0/

**Comment by yukarri805** [comment]
参考１：https://opiyotan.hatenablog.com/entry/rails-tips-metadeta_with_gem_breadcrumbs
参考２：https://pg-happy.jp/rails-pankuzu-list.html

**Comment by tomoki171923** [comment]
#73 
でパンくずリスト自体は作成済み。
残作業はgoogleの構造化データで読みとれるようにする

**Comment by tomoki171923** [comment]
#77 
でGoogleの構造化データ読み取り対応も完了。
CSSが少し壊れているのでそこだけ残タスク。

**Comment by tomoki171923** [comment]
#84 
でCSS修正済み。
クローズ。
